baseURL = "https://dgrpix.com"
languageCode = "en-us"
title = "nerdy thoughts from retirement"
theme = "PaperMod"

[params]
  description = "retired tech nerd's travels, photos, and other writing"
  author = "doug"
  defaultTheme = "dark"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowToc = false

[params.cover]
  responsiveImages = true

[params.homeInfoParams]
  Title = "welcome and apologies in advance"
  Content = "just out here doing my best, mostly for myself"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/dgrpix"

[[params.socialIcons]]
  name = "threads"
  url = "https://www.threads.net/@dgrpix"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
